import { $, state } from './state/state.js';
import { render } from './catalog/render.js';
import { toggleFavorite } from './favorites/favorites.js';
import { clearFilters, updateFavButtons } from './catalog/filters.js';
import { addToCart, qty, removeItem, updateCart } from './cart/cart.js';
import { openDetail, unlockPage, openCart, closeCart } from './modal/modal.js';
import { addCombo, renderCombo } from './combo/combo.js';
import { initNavigation, initFilters, initSearch } from './navigation/navigation.js';

// Compatibility layer for the small inline handlers generated by catalog cards.
window.toggleFav=toggleFavorite;
window.clearFilters=()=>{clearFilters();render();updateFavButtons()};
window.addToCart=addToCart;
window.qty=qty;
window.removeItem=removeItem;
window.openDetail=openDetail;
window.unlockPage=unlockPage;

const slides=[...document.querySelectorAll('.hero-slide')];
let slide=0;
const siteHeader=document.querySelector('header');
function syncHeroHeaderContrast(){
  siteHeader.classList.remove('header-contrast-light');
  const logoImg=document.querySelector('.logo-image');
  if(logoImg) logoImg.src='img/kova-k-blanca-transparente.png';
}
syncHeroHeaderContrast();
setInterval(()=>{slides[slide]?.classList.remove('active');slide=(slide+1)%slides.length;slides[slide]?.classList.add('active');syncHeroHeaderContrast()},5500);

function initCartAndModal(){
  $('cartToggle').addEventListener('click',openCart);
  $('closeCart').addEventListener('click',closeCart);
  $('overlay').addEventListener('click',closeCart);
  $('detailClose').addEventListener('click',()=>{$('detailModal').classList.remove('open');unlockPage()});
  $('detailModal').addEventListener('click',e=>{if(e.target.id==='detailModal'){$('detailModal').classList.remove('open');unlockPage()}});
}

function init(){
  initSearch();
  initFilters();
  initNavigation();
  initCartAndModal();
  $('addCombo').addEventListener('click',addCombo);
  renderCombo();
  render();
  updateCart();
}

init();
